CinemaExperience/Controllers/ActorController.cs
using CinemaExperience.Core.Contracts;
using CinemaExperience.Core.Services;
using CinemaExperience.Core.ViewModels.Actor;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using static CinemaExperience.Infrastructure.Data.Constants.DataConstants;
using static CinemaExperience.Infrastructure.Data.Constants.RoleConstants;

namespace CinemaExperience.Controllers;

public class ActorController : BaseController
{
    private readonly IActorService actorService;
    private readonly IMovieService movieService;

    public ActorController(IActorService _actorService,
        IMovieService _movieService)
    {
        actorService = _actorService;
        movieService = _movieService;
    }

    [HttpGet]
    public async Task<IActionResult> All()
    {
        var model = await actorService.GetAllActorsAsync();

        if (model == null)
        {
            return NotFound();
        }

        return View(model);
    }

    [HttpGet]
    public async Task<IActionResult> Details(int id)
    {
        var model = await actorService.GetActorDetailsAsync(id);

        if (model == null)
        {
            return NotFound();
        }

        return View(model);
    }

    [HttpGet]
    [Authorize(Roles = AdminRoleName)]
    public async Task<IActionResult> Add()
    {
        var model = new ActorViewModel()
        {
            Movies = await movieService.GetMoviesForFormAsync()
        };
        return View(model);
    }

    [HttpPost]
    [Authorize(Roles = AdminRoleName)]
    public async Task<IActionResult> Add(ActorViewModel actorForm)
    {
        if (actorForm == null)
        {
            return BadRequest();
        }

        DateTime currentDate = DateTime.Now;
        if (actorForm.BirthDate > currentDate)
        {
            ModelState.AddModelError(nameof(actorForm.BirthDate), BirthDateErrorMessage);
        }

        if (!ModelState.IsValid)
        {
            return View(actorForm);
        }

        var actorId = await actorService.AddActorAsync(actorForm);

        if (actorId == 0)
        {
            return BadRequest();
        }

        return RedirectToAction(nameof(All));
    }

    [HttpGet]
    [Authorize(Roles = AdminRoleName)]
    public async Task<IActionResult> Edit(int id)
    {
        if (!await actorService.ActorExistsAsync(id))
        {
            return BadRequest();
        }

        var model = await actorService.EditGetAsync(id);
        model.Movies = await movieService.GetMoviesForFormAsync();

        return View(model);
    }

    [HttpPost]
    [Authorize(Roles = AdminRoleName)]
    public async Task<IActionResult> Edit(ActorViewModel actorForm)
    {

        if (!await actorService.ActorExistsAsync(actorForm.Id))
        {
            return BadRequest();
        }

        DateTime currentDate = DateTime.Now;
        if (actorForm.BirthDate > currentDate)
        {
            ModelState.AddModelError(nameof(actorForm.BirthDate), BirthDateErrorMessage);
        }

        if (!ModelState.IsValid)
        {
            actorForm.Movies = await movieService.GetMoviesForFormAsync();
            return View(actorForm);
        }

        var actorId = await actorService.EditPostAsync(actorForm);

        if (actorId == 0)
        {
            return BadRequest();
        }

        return RedirectToAction(nameof(Details), new {id = actorForm.Id});
    }

    [HttpGet]
    [Authorize(Roles = AdminRoleName)]
    public async Task<IActionResult> Delete(int id)
    {
        if (!await actorService.ActorExistsAsync(id))
        {
            return BadRequest();
        }

        var model = await actorService.DeleteAsync(id);

        return View(model);
    }

    [HttpPost]
    [Authorize(Roles = AdminRoleName)]
    public async Task<IActionResult> DeleteConfirmed(int id)
    {
        if (!await actorService.ActorExistsAsync(id))
        {
            return BadRequest();
        }

        var directorId = await actorService.DeleteConfirmedAsync(id);

        return RedirectToAction(nameof(All));
    }

    [HttpGet]
    public async Task<IActionResult> Search(string input)
    {
        if (input == null)
        {
            return RedirectToAction(nameof(All));
        }

        var searchedActor = await actorService.SearchAsync(input);

        if (searchedActor == null)
        {
            return RedirectToAction(nameof(All));
        }

        return View(searchedActor);
    }
}

CinemaExperience/Controllers/DirectorController.cs
using CinemaExperience.Core.Contracts;
using CinemaExperience.Core.Services;
using CinemaExperience.Core.ViewModels.Director;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using static CinemaExperience.Infrastructure.Data.Constants.DataConstants;
using static CinemaExperience.Infrastructure.Data.Constants.RoleConstants;

namespace CinemaExperience.Controllers;

public class DirectorController : BaseController
{
    private readonly IDirectorService directorService;

    public DirectorController(IDirectorService _directorService)
    {
        directorService = _directorService;
    }

    [HttpGet]
    public async Task<IActionResult> All()
    {
        var model = await directorService.GetAllDirectorsAsync();

        if (model == null)
        {
            return NotFound();
        }

        return View(model);
    }
    [HttpGet]
    public async Task<IActionResult> Details(int id)
    {
        var model = await directorService.GetDirectorDetailsAsync(id);

        if (model == null)
        {
            return NotFound();
        }

        return View(model);
    }

    [HttpGet]
    [Authorize(Roles = AdminRoleName)]
    public async Task<IActionResult> Add()
    {
        var model = new DirectorViewModel();
        return View(model);
    }

    [HttpPost]
    [Authorize(Roles = AdminRoleName)]
    public async Task<IActionResult> Add(DirectorViewModel directorForm)
    {
        if (directorForm == null)
        {
            return BadRequest();
        }
        DateTime currentDate = DateTime.Now;
        if (directorForm.BirthDate > currentDate)
        {
            ModelState.AddModelError(nameof(directorForm.BirthDate), BirthDateErrorMessage);
        }
        if (!ModelState.IsValid)
        {
            return View(directorForm);
        }

        var directorId = await directorService.AddDirectorAsync(directorForm);

        if (directorId == 0)
        {
            return BadRequest();
        }

        return RedirectToAction(nameof(All));
    }

    [HttpGet]
    [Authorize(Roles = AdminRoleName)]
    public async Task<IActionResult> Edit(int id)
    {
        if (!await directorService.DirectorExistsAsync(id)) 
        { 
            return BadRequest();
        }

        var model = await directorService.EditGetAsync(id);


        return View(model);
    }

    [HttpPost]
    [Authorize(Roles = AdminRoleName)]
    public async Task<IActionResult> Edit(DirectorViewModel directorForm)
    {
        if (!await directorService.DirectorExistsAsync(directorForm.Id))
        {
            return BadRequest();
        }
        DateTime currentDate = DateTime.Now;
        if (directorForm.BirthDate > currentDate)
        {
            ModelState.AddModelError(nameof(directorForm.BirthDate), BirthDateErrorMessage);
        }
        if (!ModelState.IsValid)
        {
            return View(directorForm);
        }

        var directorId = await directorService.EditPostAsync(directorForm);

        return RedirectToAction(nameof(All));
    }

    [HttpGet]
    [Authorize(Roles = AdminRoleName)]
    public async Task<IActionResult> Delete(int id)
    {
        if (!await directorService.DirectorExistsAsync(id))
        {
            return BadRequest();
        }

        var model = await directorService.DeleteAsync(id);

        return View(model);
    }

    [HttpPost]
    [Authorize(Roles = AdminRoleName)]
    public async Task<IActionResult> DeleteConfirmed(int id)
    {
        if (!await directorService.DirectorExistsAsync(id))
        {
            return BadRequest();
        }

        var directorId = await directorService.DeleteConfirmedAsync(id);

        return RedirectToAction(nameof(All));
    }

    [HttpGet]
    public async Task<IActionResult> Search(string input)
    {
        if (input == null)
        {
            return RedirectToAction(nameof(All));
        }

        var searchedDirector = await directorService.SearchAsync(input);

        if (searchedDirector == null)
        {
            return RedirectToAction(nameof(All));
        }

        return View(searchedDirector);
    }
}

CinemaExperience/Controllers/MovieController.cs
using CinemaExperience.Core.Contracts;
using CinemaExperience.Core.Extensions;
using CinemaExperience.Core.ViewModels.Movie;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using static CinemaExperience.Infrastructure.Data.Constants.DataConstants;
using static CinemaExperience.Infrastructure.Data.Constants.RoleConstants;

namespace CinemaExperience.Controllers;

public class MovieController : BaseController
{
	private readonly IMovieService movieService;
	private readonly IDirectorService directorService;
	private readonly IActorService actorService;

	public MovieController(IMovieService _movieService,
		IDirectorService _directorService,
		IActorService _actorService)
	{
		movieService = _movieService;
		directorService = _directorService;
		actorService = _actorService;
	}

	[HttpGet]
	public async Task<IActionResult> All()
	{
		var model = await movieService.GetAllMoviesAsync();

		return View(model);
	}

	[HttpGet]
	public async Task<IActionResult> Details(int id, string information)
	{
		if (!await movieService.MovieExistsAsync(id))
		{
			return BadRequest();
		}

		var model = await movieService.GetMovieDetailsAsync(id);

		if (information != model.GetMovieInformation())
		{
			return BadRequest();
		}

		return View(model);
	}

	[HttpGet]
    [Authorize(Roles = AdminRoleName)]
    public async Task<IActionResult> Add()
	{
		var model = new MovieViewModel()
		{
			Directors = await directorService.GetDirectorsForFormAsync(),
			Genres = await movieService.GetGenresForFormAsync(),
			Actors = await actorService.GetActorsForFormAsync(),

		};

		return View(model);
	}

	[HttpPost]
    [Authorize(Roles = AdminRoleName)]
    public async Task<IActionResult> Add(MovieViewModel movieForm)
	{
		if (await directorService.DirectorExistsAsync(movieForm.DirectorId) == false)
		{
			ModelState.AddModelError(nameof(movieForm.DirectorId), DirectorErrorMessage);
		}
		foreach (var genreId in movieForm.GenreIds)
		{
            if (await movieService.GenreExistsAsync(genreId) == false)
            {
                ModelState.AddModelError(nameof(movieForm.GenreIds), GenreNoExistErrorMessage);
            }
        }
		if (movieForm.GenreIds.Count() < 1)
		{
			ModelState.AddModelError(nameof(movieForm.GenreIds), AtLeastOneGenreErrorMessage);
		}

		if (!ModelState.IsValid)
		{
			movieForm.Directors = await directorService.GetDirectorsForFormAsync();
			movieForm.Genres = await movieService.GetGenresForFormAsync();
			movieForm.Actors = await actorService.GetActorsForFormAsync();
			return View(movieForm);
		}

		int movieId = await movieService.AddMovieAsync(movieForm);
		return RedirectToAction(nameof(All));
	}

	[HttpGet]
    [Authorize(Roles = AdminRoleName)]
    public async Task<IActionResult> Edit(int id, string information)
	{
		if (!await movieService.MovieExistsAsync(id))
		{
			return BadRequest();
		}

		var model = await movieService.EditGetAsync(id);
        model.Directors = await directorService.GetDirectorsForFormAsync();
        model.Actors = await actorService.GetActorsForFormAsync();

        if (model.GetMovieInformation() != information)
		{
			return BadRequest();
		}

		return View(model);
	}

	[HttpPost]
    [Authorize(Roles = AdminRoleName)]
    public async Task<IActionResult> Edit(MovieViewModel movieForm)
	{
		if (!await movieService.MovieExistsAsync(movieForm.Id))
		{
			return BadRequest();
		}

		if (await directorService.DirectorExistsAsync(movieForm.DirectorId) == false)
		{
			ModelState.AddModelError(nameof(movieForm.DirectorId), DirectorErrorMessage);
		}
        foreach (var genreId in movieForm.GenreIds)
        {
            if (await movieService.GenreExistsAsync(genreId) == false)
            {
                ModelState.AddModelError(nameof(movieForm.GenreIds), GenreNoExistErrorMessage);
            }
        }
        if (movieForm.GenreIds.Count() < 1)
		{
			ModelState.AddModelError(nameof(movieForm.GenreIds), AtLeastOneGenreErrorMessage);
		}

		if (!ModelState.IsValid)
		{
			movieForm.Directors = await directorService.GetDirectorsForFormAsync();
			movieForm.Genres = await movieService.GetGenresForFormAsync();
			movieForm.Actors = await actorService.GetActorsForFormAsync();
			return View(movieForm);
		}

		int movieId = await movieService.EditPostAsync(movieForm);

		return RedirectToAction(nameof(Details), new { id = movieForm.Id, information = movieForm.GetMovieInformation() });
	}

	[HttpGet]
	public async Task<IActionResult> Search(string input)
	{
		if (input == null)
		{
			return RedirectToAction(nameof(All));
		}

		var searchedMovie = await movieService.SearchAsync(input);

		if (searchedMovie == null)
		{
			return RedirectToAction(nameof(All));
		}

		return View(searchedMovie);
	}

	[HttpGet]
    [Authorize(Roles = AdminRoleName)]
    public async Task<IActionResult> Delete(int id, string information)
	{
		if (!await movieService.MovieExistsAsync(id))
		{
			return BadRequest();
		}

		var movieToDelete = await movieService.DeleteAsync(id);

		if (movieToDelete.GetMovieInformation() != information)
		{
            return BadRequest();
        }

		return View(movieToDelete);
	}

	[HttpPost]
    [Authorize(Roles = AdminRoleName)]
    public async Task<IActionResult> DeleteConfirmed(int id)
	{
		if (!await movieService.MovieExistsAsync(id))
		{
			return BadRequest();
		}

		await movieService.DeleteConfirmedAsync(id);

		return RedirectToAction(nameof(All));
	}



}

CinemaExperience/Controllers/ReviewController.cs
using CinemaExperience.Core.Contracts;
using CinemaExperience.Core.ViewModels.Review;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;

namespace CinemaExperience.Controllers;

public class ReviewController : BaseController
{
    private readonly IReviewService reviewService;

    public ReviewController(IReviewService _reviewService)
    {
        reviewService = _reviewService;
    }

    [HttpGet]
    public async Task<IActionResult> All(int Id)
    {
        var reviews = await reviewService.GetAllReviewsByMovieIdAsync(Id);

        return View(reviews);
    }

    [HttpGet]
    public IActionResult Add(int Id)
    {
        var reviewForm = new ReviewViewModel
        {
            MovieId = Id,
            UserId = User.Id()
        };

        return View(reviewForm);
    }

    [HttpPost]
    public async Task<IActionResult> Add(ReviewViewModel reviewForm)
    {
        if (reviewForm == null)
        {
            return BadRequest();
        }
        if (!ModelState.IsValid)
        {
            return View(reviewForm);
        }

        var reviewId = await reviewService.AddReviewAsync(reviewForm);

        return RedirectToAction(nameof(All), new {id = reviewForm.MovieId});
    }

    [HttpGet]
    public async Task<IActionResult> Edit(int Id)
    {
        var reviewForm = await reviewService.EditReviewGetAsync(Id);

        if (reviewForm == null)
        {
            return BadRequest();
        }
        if (User.Id() != reviewForm.UserId && !User.IsAdmin())
        {
            return Unauthorized();
        }
        if (!ModelState.IsValid)
        {
            return View(reviewForm);
        }

        return View(reviewForm);
    }

    [HttpPost]
    public async Task<IActionResult> Edit(ReviewViewModel reviewForm)
    {
        if (reviewForm == null)
        {
            return BadRequest();
        }
        if (User.Id() != reviewForm.UserId && !User.IsAdmin())
        {
            return Unauthorized();
        }
        if (!ModelState.IsValid)
        {
            return View(reviewForm);
        }

        var reviewId = await reviewService.EditReviewPostAsync(reviewForm);

        return RedirectToAction(nameof(All), new {id = reviewForm.MovieId});
    }

    [HttpGet]
    public async Task<IActionResult> Delete(int Id)
    {
        var reviewForm = await reviewService.DeleteAsync(Id);

        if (!await reviewService.ReviewExistsAsync(reviewForm.Id))
        {
            return BadRequest();
        }
        if (User.Id() != reviewForm.UserId && !User.IsAdmin())
        {
            return Unauthorized();
        }

        return View(reviewForm);
    }

    [HttpPost]
    public async Task<IActionResult> DeleteConfirmed(ReviewDeleteViewModel reviewForm)
    {
        if (!await reviewService.ReviewExistsAsync(reviewForm.Id))
        {
            return BadRequest();
        }
        if (User.Id() != reviewForm.UserId && !User.IsAdmin())
        {
            return Unauthorized();
        }

        var reviewId = await reviewService.DeleteConfirmedAsync(reviewForm.Id);

        return RedirectToAction(nameof(All), new {id = reviewForm.MovieId});
    }
}

CinemaExperience/Views/Shared/_ActorAllPartial.cshtml
@model IEnumerable<AllActorsViewModel>

@if (User.IsInRole(AdminRoleName))
{
    <div class="text-center mb-3">
        <a href="@Url.Action("Add", "Actor")" class="btn btn-primary">Add Actor</a>
    </div>
}

<hr />

<partial name="_ActorSearchFormPartial" />

<div class="directors-list">
    @if (Model !=null && Model.Any())
    {
        @foreach (var actors in Model)
        {
        <div class="col-md-2">
            <div class="card mb-4 shadow-sm">
                <img class="bd-placeholder-img card-img-top" width="100%" src="@actors.ImageUrl" alt="@actors.Name">
                <div class="card-body d-flex flex-column">
                    <p class="card-text">@actors.Name</p>
                    <div class="btn-group">
                        <a href="@Url.Action("Details", "Actor", new { id = actors.Id })" class="btn btn-sm btn-outline-secondary">Details</a>
                        @if (User.IsInRole(AdminRoleName))
                        {
                            <a href="@Url.Action("Edit", "Actor", new { id = actors.Id })" class="btn btn-sm btn-outline-secondary">Edit</a>
                            <a href="@Url.Action("Delete", "Actor", new { id = actors.Id })" class="btn btn-sm btn btn-danger">Delete</a>
                        }
                    </div>
                </div>
            </div>
        </div>
        }
    }
    else
	{
		<div class="col-md-12">
			<h2 class="text-center">No Actors yet</h2>
		</div>
	}
</div>

CinemaExperience/Views/Shared/_ActorSearchFormPartial.cshtml
<div class="text-center mb-4">
    <form asp-controller="Actor" asp-action="Search" method="get" class="row">
        <div class="col-md-11">
            <div class="input-group">
                <input type="text" name="input" class="form-control" placeholder="Search" />
                <div class="input-group-append">
                    <button type="submit" class="btn btn-warning">Search</button>
                    <a asp-controller="Actor" asp-action="All" class="btn btn-secondary">Clear</a>
                </div>
            </div>
        </div>
    </form>
</div>

CinemaExperience/Views/Shared/_ActorSearchPartial.cshtml
@model IEnumerable<AllActorsViewModel>

<div class="container">
    <partial name="_ActorSearchFormPartial"/>
</div>
    <div class="directors-list">
    @foreach (var actors in Model)
    {
        <div class="col-md-2">
            <div class="card mb-4 shadow-sm">
                <img class="bd-placeholder-img card-img-top" width="100%" src="@actors.ImageUrl" alt="@actors.Name">
                <div class="card-body d-flex flex-column">
                    <p class="card-text">@actors.Name</p>
                    <div class="btn-group">
                        <a href="@Url.Action("Details", "Actor", new { id = actors.Id })" class="btn btn-sm btn-outline-secondary">Details</a>
                        @if (User.IsInRole(AdminRoleName))
                        {
                            <a href="@Url.Action("Edit", "Actor", new { id = actors.Id })" class="btn btn-sm btn-outline-secondary">Edit</a>
                            <a href="@Url.Action("Delete", "Actor", new { id = actors.Id })" class="btn btn-sm btn btn-danger">Delete</a>
                        }
                    </div>
                </div>
            </div>
        </div>
    }
    </div>

CinemaExperience/Views/Shared/_DirectorAllPartial.cshtml
@model IEnumerable<AllDirectorsViewModel>

@if (User.IsInRole(AdminRoleName))
{
    <div class="text-center mb-3">
        <a href="@Url.Action("Add", "Director")" class="btn btn-primary">Add Director</a>
    </div>
}

<hr />

<partial name="_DirectorSearchFormPartial" />

<div class="directors-list">
    @foreach (var director in Model)
    {
        <div class="col-md-2">
            <div class="card mb-4 shadow-sm">
                <img class="bd-placeholder-img card-img-top" width="100%" src="@director.ImageUrl" alt="@director.Name">
                <div class="card-body d-flex flex-column">
                    <p class="card-text">@director.Name</p>
                    <div class="btn-group">
                        <a href="@Url.Action("Details", "Director", new { id = director.Id })" class="btn btn-sm btn-outline-secondary">Details</a>
                        @if (User.IsInRole(AdminRoleName))
                        {
                            <a href="@Url.Action("Edit", "Director", new { id = director.Id })" class="btn btn-sm btn-outline-secondary">Edit</a>
                            <a href="@Url.Action("Delete", "Director", new { id = director.Id })" class="btn btn-sm btn btn-danger">Delete</a>
                        }
                    </div>
                </div>
            </div>
        </div>
    }
</div>

CinemaExperience/Views/Shared/_DirectorSearchFormPartial.cshtml
<div class="text-center mb-4">
    <form asp-controller="Director" asp-action="Search" method="get" class="row">
        <div class="col-md-11">
            <div class="input-group">
                <input type="text" name="input" class="form-control" placeholder="Search" />
                <div class="input-group-append">
                    <button type="submit" class="btn btn-warning">Search</button>
                    <a asp-controller="Director" asp-action="All" class="btn btn-secondary">Clear</a>
                </div>
            </div>
        </div>
    </form>
</div>

CinemaExperience/Views/Shared/_DirectorSearchPartial.cshtml
@model IEnumerable<AllDirectorsViewModel>

<div class="container">
	<partial name="_DirectorSearchFormPartial"/>


    <div class="directors-list">
        @if(Model != null && Model.Any())
		{
            @foreach (var director in Model)
            {
            <div class="col-md-2">
                <div class="card mb-4 shadow-sm">
                    <img class="bd-placeholder-img card-img-top" width="100%" src="@director.ImageUrl" alt="@director.Name">
                    <div class="card-body d-flex flex-column">
                        <p class="card-text">@director.Name</p>
                        <div class="btn-group">
                            <a href="@Url.Action("Details", "Director", new { id = director.Id })" class="btn btn-sm btn-outline-secondary">Details</a>
                            @if (User.IsInRole(AdminRoleName))
                            {
                                <a href="@Url.Action("Edit", "Director", new { id = director.Id })" class="btn btn-sm btn-outline-secondary">Edit</a>
                                <a href="@Url.Action("Delete", "Director", new { id = director.Id })" class="btn btn-sm btn btn-danger">Delete</a>
                            }
                        </div>
                    </div>
                </div>
            </div>
            }
        }
		else
		{
			<div class="col-md-12">
				<h2 class="text-center">No Directors yet</h2>
			</div>
		}
    </div>
</div>

CinemaExperience/Views/Shared/_MovieAllPartial.cshtml
@model IEnumerable<AllMoviesViewModel>

@if (User.IsInRole(AdminRoleName))
{
    <div class="text-center mb-3">
        <a href="@Url.Action("Add", "Movie")" class="btn btn-primary">Add Movie</a>
    </div>
}

<hr />

<partial name="_MovieSearchFormPartial" />

<div class="container">
    <div class="row">
        @if (Model != null && Model.Any())
        {
            @foreach (var movie in Model)
            {
                <div class="col-md-4">
                    <div class="card mb-4 shadow-sm">
                        <img class="bd-placeholder-img card-img-top" width="100%" src="@movie.ImageUrl" alt="@movie.Title">
                        <div class="card-body">
                            <p class="card-text">@movie.Title</p>
                            <p class="card-text"><small class="text-muted">@movie.Director</small></p>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    <a href="@Url.Action("Details", "Movie", new { id = movie.Id, information = movie.GetMovieInformation() })" class="btn btn-sm btn-outline-secondary">Details</a>
                                    @if (User.IsInRole(AdminRoleName))
                                    {
                                        <a href="@Url.Action("Edit", "Movie", new { id = movie.Id, information = movie.GetMovieInformation() })" class="btn btn-sm btn-outline-secondary">Edit</a>
                                        <a href="@Url.Action("Delete", "Movie", new { id = movie.Id, information = movie.GetMovieInformation() })" class="btn btn-sm btn btn-danger">Delete</a>
                                    }
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            }
        }
        else
        {
            <div class="col-md-12">
                <h2 class="text-center">No movies found</h2>
            </div>
        }
    </div>
</div>

CinemaExperience/Views/Shared/_MovieSearchFormPartial.cshtml
<div class="text-center mb-4">
    <form asp-controller="Movie" asp-action="Search" method="get" class="row">
        <div class="col-md-11">
            <div class="input-group">
                <input type="text" name="input" class="form-control" placeholder="Search" />
                <div class="input-group-append">
                    <button type="submit" class="btn btn-warning">Search</button>
                    <a asp-controller="Movie" asp-action="All" class="btn btn-secondary">Clear</a>
                </div>
            </div>
        </div>
    </form>
</div>

CinemaExperience/Views/Shared/_MovieSearchPartial.cshtml
@model IEnumerable<AllMoviesViewModel>

<div class="container">
	<partial name="_MovieSearchFormPartial"/>

    <div class="container">
        <div class="row">
            @if (Model != null && Model.Any())
            {
                @foreach (var movie in Model)
                {
                    <div class="col-md-4">
                        <div class="card mb-4 shadow-sm">
                            <img class="bd-placeholder-img card-img-top" width="100%" src="@movie.ImageUrl" alt="@movie.Title">
                            <div class="card-body">
                                <p class="card-text">@movie.Title</p>
                                <p class="card-text"><small class="text-muted">@movie.Director</small></p>
                                <div class="d-flex justify-content-between align-items-center">
                                    <div class="btn-group">
                                        <a href="@Url.Action("Details", "Movie", new { id = movie.Id })" class="btn btn-sm btn-outline-secondary">Details</a>
                                        @if (User.IsInRole(AdminRoleName))
                                        {
                                            <a href="@Url.Action("Edit", "Movie", new { id = movie.Id })" class="btn btn-sm btn-outline-secondary">Edit</a>
                                        }
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                }
            }
            else
            {
                <div class="col-md-12">
                    <h2 class="text-center">No movies found</h2>
                </div>
            }
        </div>
    </div>
</div>

CinemaExperience/Views/Shared/_ReviewFormPartial.cshtml
@model ReviewViewModel

<div class="row">
    <div class="col-sm-12 offset-lg-2 col-lg-8 offset-xl-3 col-xl-6">
        <form method="post">
            <input type="hidden" asp-for="MovieId" value="@Model.MovieId" />
            <input type="hidden" asp-for="UserId" value="@Model.UserId" />
            <input type="hidden" asp-for="Id" value="@Model.Id" />
            <div class="mb-3">
                <label asp-for="@Model.Content" class="form-label-add-edit"><bold>Content</bold></label>
                <textarea asp-for="@Model.Content" class="form-control" aria-required="true" rows="5"></textarea>
                <span asp-validation-for="@Model.Content" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="@Model.Rating" class="form-label-add-edit"><bold>Rating (1-10)</bold></label>
                <select asp-for="@Model.Rating" class="form-control" aria-required="true">
                    <option disabled selected value="">Rate...</option>
                    @for (int i = 1; i <= 10; i++)
                    {
                        <option value="@i">@i</option>
                    }
                </select>
                <span asp-validation-for="@Model.Rating" class="text-danger"></span>
            </div>
            <div class="mb-3">
                @{
                    var id = Model.MovieId;
                }
                <a asp-controller="Review" asp-action="All" asp-route-id="@id" class="btn btn-warning mb-2 w-100 p-3 fw-bold">Back to all reviews</a>
                <input class="btn btn-success mb-2 w-100 p-3 fw-bold" type="submit" value="Add" />
            </div>
        </form>
    </div>
</div>